import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Platform } from 'react-native';
import * as SecureStore from 'expo-secure-store';

const storage = {
  getItem: async (key: string): Promise<string | null> => {
    if (Platform.OS === 'web') return localStorage.getItem(key);
    return SecureStore.getItemAsync(key);
  },
  setItem: async (key: string, value: string): Promise<void> => {
    if (Platform.OS === 'web') { localStorage.setItem(key, value); return; }
    return SecureStore.setItemAsync(key, value);
  },
};

export type Locale = 'en' | 'ms';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Locale, Record<string, string>> = {
  en: {
    merchant_portal: "Merchant Portal",
    merchant_console: "Merchant Console",
    loyalty_wallet: "Loyalty Wallet",
    home: "Home",
    explore: "Explore",
    vouchers: "Vouchers",
    history: "History",
    customers: "Customers",
    scan_member: "Scan Member",
    marketing: "Marketing",
    quick_actions: "Quick Actions",
    recent_activity: "Recent Activity",
    active_promotions: "Active Promotions",
    welcome_back: "Welcome back",
    total_stamps_awarded: "Total Stamps Awarded",
    scan_customer_qr: "Scan Customer QR",
    this_months_sales: "This Month's Sales",
    goal: "goal",
    to_go: "to go!",
    recent_stamps_issued: "Recent Stamps Issued",
    see_all: "See All",
    no_recent_activities: "No Recent Activities",
    stamps_issued_desc: "Stamps issued during this period will show up here.",
    stamps_label: "stamps",
    today: "Today",
    this_week: "This Week",
    this_month: "This Month",
    every_visit_rewarded: "Every visit, rewarded.",
    show_my_qr_code: "Show My QR Code",
    discover_shops: "Discover Shops",
    my_stamp_cards: "My Stamp Cards",
    add_card: "Add Card",
    no_active_cards: "No Active Cards",
    no_active_cards_desc: "Start visiting our partner merchants to collect stamps and earn rewards!",
    promo_title: "2x Stamps Weekend",
    promo_badge: "LIMITED",
    promo_desc: "Visit any RISEV partner shop this weekend and earn double stamps!",
    explore_now: "Explore Now",
    profile: "Profile",
    // Customers Screen
    transaction_history: "Transaction History",
    total_stamps_distributed: "Total Stamps Distributed",
    from_last_month: "from last month",
    points_redeemed: "Points Redeemed",
    rewards_claimed: "rewards claimed by customers",
    active_members: "Active Members",
    no_active_members: "No active members",
    search_customer: "Search Customer...",
    all: "All",
    purchase: "Purchase",
    redemption: "Redemption",
    adjustment: "Adjustment",
    date_time: "DATE & TIME",
    customer: "CUSTOMER",
    type: "TYPE",
    pending: "Pending",
    success: "Success",
    no_transactions: "No Transactions",
    no_transactions_desc: "No customer transactions matched your filters.",
    customer_details: "Customer Details",
    phone: "Phone",
    joined: "Joined",
    tier_label: "Tier",
    stamps_collected: "Stamps Collected",
    points_balance: "Points Balance",
    active_vouchers: "Active Vouchers",
    export_data: "Export Data",
    download_csv: "Download CSV",
    date_filter: "Date Filter",
    all_time: "All Time",
    yesterday: "Yesterday",
    last_7_days: "Last 7 Days",
    last_30_days: "Last 30 Days",
    sort_by: "Sort By",
    newest: "Newest First",
    oldest: "Oldest First",
    customer_profile: "Customer Profile",
    redemption_details: "Redemption Details",
    reward_item: "Reward Item",
    voucher_code: "Voucher Code",
    redeemed_at: "Redeemed At",
    stamp_card_progress: "STAMP CARD PROGRESS",
    current_stamps: "Current Stamps",
    total_completions: "Total Completions",
    completed: "Completed",
    no_active_card_desc: "No active stamp card started yet.",
    rewards_vouchers: "REWARDS & VOUCHERS",
    no_vouchers_desc: "No vouchers issued for this customer.",
    visit_history: "VISIT HISTORY",
    earned_stamp: "Earned Stamp",
    redeemed_reward: "Redeemed Reward",
    no_visits_desc: "No visits logged.",
    filter_by_date: "Filter by Date",
    sort_preferences: "Sort Preferences",
    sort_by_date: "SORT BY DATE",
    export_data_csv: "Export Data to CSV",
    compiling_csv: "Compiling CSV export file...",
    customer_database: "Customer Database",
    customer_database_sub: "Includes names, phone numbers, tiers, and points balance.",
    filtered_transactions: "Filtered Transactions",
    filtered_transactions_sub: "Exports only records matching current filter settings.",
    all_time_transactions: "All-Time Transactions",
    all_time_transactions_sub: "Full transaction history logs including subtotal sale amounts.",
    // Scan / Manual Input
    scan_qr_code: "Scan QR Code",
    manual_input: "Manual Input",
    scan_subtitle: "Align the customer's QR code within the viewfinder frame to credit stamp points automatically.",
    manual_stamp_or_voucher: "Manual Stamp or Voucher",
    manual_subtitle: "Enter customer's phone number to credit stamps, or enter a voucher code (starts with WV- or RV-) to redeem.",
    phone_number_or_voucher: "PHONE NUMBER OR VOUCHER CODE",
    phone_or_voucher_placeholder: "+60123456789 or WV-XXXX/RV-XXXX",
    bill_subtotal: "BILL SUBTOTAL (RM)",
    stamps_to_issue: "NUMBER OF STAMPS TO ISSUE",
    issue_stamps_btn: "Issue Stamp Points",
    submitting: "Submitting...",
    issue_success_title: "Stamps Issued Successfully!",
    issue_success_desc: "Successfully credited stamps to the customer.",
    camera_permission_required: "Camera access is required to scan QR codes.",
    enable_camera: "Enable Camera",
    redeem_voucher: "Redeem Voucher",
    voucher_redeemed_upper: "VOUCHER REDEEMED!",
    stamps_awarded_upper: "STAMPS AWARDED!",
    awarded: "Awarded",
    bill_amount: "Bill Amount",
    current_balance: "Current Balance",
    reward: "Reward",
    done: "DONE",
    new_customer_profile: "NEW CUSTOMER PROFILE",
    customer_name_optional: "CUSTOMER NAME (OPTIONAL)",
    customer_name_placeholder: "Enter name (e.g. Adam)",
    create_issue: "Create & Issue",
    campaign_inactive: "CAMPAIGN INACTIVE",
    campaign_inactive_desc: "No active loyalty program found for your store. Please go to the Marketing section to create a campaign and enable it first.",
    close: "Close",
    go_to_marketing: "Go to Marketing",
    // Marketing Screen
    promotions: "Promotions",
    broadcast: "Broadcast",
    marketing_campaigns: "Marketing Campaigns",
    marketing_subtitle: "Drive shop sales with multipliers and points promotions.",
    new_btn: "+ New",
    no_active_promotions: "No active promotions yet",
    no_promotions_desc: "Launch a double points or flat bonus campaign to attract customers to your store.",
    create_campaign: "Create Campaign",
    whatsapp_disconnected: "WhatsApp Disconnected",
    whatsapp_disconnected_desc: "Please link your store WhatsApp in your Profile Settings to send promotions.",
    instant_blast: "Instant Blast",
    auto_follow_up: "Auto Follow-Up",
    compose_broadcast: "Compose Broadcast Blast",
    compose_subtitle: "Customize a promotion template or type a custom update.",
    link_campaign: "LINK CAMPAIGN (OPTIONAL)",
    no_campaign_link: "No Campaign Link",
    broadcast_title: "BROADCAST TITLE",
    message_body: "MESSAGE BODY (TEMPLATED)",
    send_broadcast: "Send Broadcast",
    promotion_type: "PROMOTION TYPE",
    campaign_period: "CAMPAIGN PERIOD",
    redemptions: "Redemptions",
    unlimited_placeholder: "Unlimited if left empty",
    template_helper_desc: "Use {{name}} for customer name and {{stamps}} for collected stamps count.",
    send_whatsapp_message: "Send WhatsApp Message",
    whatsapp_blast_desc: "Delivers high-engagement chats in addition to app push alerts.",
    send_broadcast_btn: "Send Broadcast Blast",
    broadcast_history: "BROADCAST HISTORY",
    no_broadcasts_sent: "No broadcasts sent yet",
    no_broadcasts_desc: "Link your WhatsApp and send your first promotional blast!",
    sent_on: "Sent on",
    recipients: "RECIPIENTS",
    follow_up: "Follow Up",
    follow_up_on: "Follow-up on",
    edit_automation_rule: "Edit Retention Follow-Up Rule",
    automated_winback: "Automated Win-Back Follow-Up",
    automation_desc: "Automatically alert customers after they are inactive for a set number of days since their last visit/stamp.",
    trigger_delay: "TRIGGER DELAY INACTIVITY",
    days: "Days",
    custom: "Custom",
    custom_days_placeholder: "Enter custom number of days (e.g. 10)",
    rule_name: "RULE NAME",
    message_title: "MESSAGE TITLE",
    send_via_whatsapp: "Send via WhatsApp",
    whatsapp_automation_desc: "Delivers notification directly to client WhatsApp when triggered.",
    update_rule: "Update Rule",
    activate_rule: "Activate Automation Rule",
    cancel_edit: "Cancel Edit",
    active_automation_rules: "ACTIVE AUTOMATION RULES",
    no_automation_rules: "No automation rules yet",
    no_automation_desc: "Define your first rule above to automatically follow up on inactive customers.",
    trigger_label: "Trigger",
    days_inactive: "Days Inactive",
    subject: "Subject",
    edit: "Edit",
    delete: "Delete",
    launch_campaign: "Launch Campaign",
    campaign_name: "CAMPAIGN NAME",
    description: "DESCRIPTION",
    point_multiplier: "POINT MULTIPLIER",
    flat_points_value: "FLAT POINTS VALUE",
    bonus_stamps_awarded: "BONUS STAMPS AWARDED",
    double_points: "Double Points",
    flat_bonus: "Flat Bonus",
    bonus_stamps: "Bonus Stamps",
    start_date: "START DATE",
    end_date: "END DATE",
    max_redemptions: "MAX REDEMPTIONS (OPTIONAL)",
    launch_promotion_btn: "Launch Promotion",
    store_owner_only: "Store Owner Only",
    store_owner_only_desc: "This configuration panel is restricted to the merchant store owner. Please contact your administrator to make design updates.",
    go_back_home: "Go Back Home",
    // Rewards Screen
    rewards_catalog: "Rewards Catalog",
    rewards_desc: "Setup and manage rewards catalog for stamp redemptions",
    create_reward: "Create Reward",
    experience: "Experience",
    cash_credit: "Cash Credit",
    catalogue_tab: "Catalogue",
    card_design_tab: "Card Design",
    points_tiers_tab: "Points & Tiers",
    loyalty_settings: "Loyalty Settings",
    rewards_loyalty_setup: "Rewards & Loyalty Setup",
    rewards_loyalty_setup_desc: "Configure your customer loyalty experience, visual card details, point rules, and catalog items.",
    catalogue_empty: "Catalogue is Empty",
    catalogue_empty_desc: "You haven't added any rewards for your customers to redeem yet. Click the \"+\" button in the top right to create your first reward!",
    add_first_reward: "Add First Reward",
    enable_loyalty_program: "Enable Loyalty Program",
    enable_loyalty_desc: "Instantly activate or pause this loyalty stamp program for your shop.",
    total_stamps_required: "Total Stamps Required",
    total_stamps_desc: "Set the number of stamp collections milestones for voucher completion.",
    card_bg_color: "Card Background Color",
    custom_hex_code: "Custom Hex Code",
    collected_slots_color: "Collected Stamp Slots Color",
    select_card_text_color: "Select Card Text Color",
    stamp_check_icon: "Stamp Check Icon",
    stamp_check_desc: "Choose the visual checkmark symbol displayed inside earned stamp slots.",
    custom_bg_image: "Custom Background Image",
    custom_bg_desc: "Upload a landscape brand image overlay for your card back. Recommended: 800x450, max 2MB.",
    upload_card_image: "Upload Card Image",
    card_settings: "Card Settings",
    card_expiration_days: "Card expiration (days)",
    stamp_completion_desc: "Stamp completion reward description",
    live_preview_card: "LIVE PREVIEW CARD",
    loyalty_card_upper: "LOYALTY CARD",
    card_holder: "CARD HOLDER",
    valid: "VALID",
    cvv: "CVV",
    save_card_config: "Save Card Configuration",
    how_points_work: "How Your Customers Earn Points",
    how_points_work_desc: "Every time a customer pays at your shop, they earn loyalty points based on how much they spend.",
    formula_label: "RM 1 spent = 1 Point",
    example_label: "📋 Example",
    example_desc: "A customer pays RM 45.50 for their order.\nThey receive 45 points added to their loyalty card — automatically!",
    points_added_info: "Points are added whenever your staff keys in a customer visit. No extra step needed from the customer.",
    membership_tiers: "Customer Membership Tiers",
    membership_tiers_desc: "Customers move up tiers based on their total spending at your shop over the past 12 months. Higher tiers earn more points per ringgit — rewarding your most loyal customers automatically.",
    bronze_desc: "New customers · Total spend below RM 100",
    silver_desc: "Regular customers · RM 100 – RM 299 spent",
    gold_desc: "Loyal customers · RM 300 – RM 499 spent",
    platinum_desc: "VIP customers · RM 500+ spent",
    points_multiplier_label: "1x Points",
    points_multiplier_silver: "1.25x Points",
    points_multiplier_gold: "1.5x Points",
    points_multiplier_platinum: "2x Points",
    why_tiers_matter: "Why tiers matter for your business",
    why_tiers_matter_desc: "Platinum customers earn 2x points per ringgit, which motivates your best spenders to keep coming back. Tiers are tracked and updated automatically — you don't need to do anything.",
    add_new_reward: "Add New Reward",
    edit_reward: "Edit Reward",
    upload_image: "Upload Image",
    reward_title: "Reward Title",
    points_cost: "Points Cost",
    stock_availability: "Stock Availability",
    reward_type: "Reward Type",
    description_terms: "Description / Terms",
    describe_terms_placeholder: "Describe the reward and redemption terms...",
    publish_reward: "Publish Reward",
    publish_reward_desc: "Make this reward immediately visible to customers.",
    save_changes: "Save Changes",
    delete_reward: "Delete Reward",
    delete_reward_confirm: "Are you sure you want to delete this reward from your catalogue? This action cannot be undone.",
    // Staff Screen
    invite_staff: "Invite Staff",
    manage_staff: "Manage Staff",
    manage_staff_desc: "Authorize staff members to manage your store, issue stamps, and process reward redemptions.",
    add_staff_desc: "Enter the customer's phone number to invite them as staff. They must already have an account on the Customer App.",
    add_btn_label: "Add",
    active_staff: "Active Staff",
    no_staff: "No Staff Added Yet",
    no_staff_desc: "You currently manage this store alone. Use the form above to add your cashiers or branch managers.",
    remove_staff: "Remove Staff Member",
    email: "EMAIL",
    role: "ROLE",
    profile_settings: "Profile & Settings",
    profile_subtitle: "Manage your store business profile and account preferences.",
    verified_partner: "VERIFIED PARTNER",
    gold_partner: "GOLD PARTNER",
    update: "Update",
    business_email: "BUSINESS EMAIL",
    phone_number: "PHONE NUMBER",
    address: "ADDRESS",
    personal_account: "Personal Account?",
    switch_customer_desc: "Switch back to customer console to view your loyalty cards and catalog rewards.",
    switch_customer_btn: "Switch to Customer Mode",
    operating_hours: "Operating Hours",
    account_settings: "Account Settings",
    link_whatsapp: "Link WhatsApp",
    link_whatsapp_desc: "Link store WhatsApp account",
    whatsapp_connected: "Connected (Tap to manage)",
    whatsapp_checking: "Checking status...",
    manage_rewards: "Manage Rewards",
    manage_rewards_desc: "Setup and manage rewards catalog",
    notifications: "Notifications",
    notifications_desc: "Push, Email & SMS Alerts",
    security: "Security",
    security_desc: "Password settings",
    language: "Language",
    language_desc: "English",
    payment_method: "Payment Method",
    payment_method_desc: "Credit & Bank Transfers",
    privacy_policy: "Privacy Policy",
    privacy_policy_desc: "Terms & Conditions",
    logout: "Log Out",
    logout_desc: "End active session",
    logout_confirm_title: "Log Out Account",
    logout_confirm_desc: "Are you sure you want to log out of your RISEV account? You will need to verify your mobile number again to sign back in.",
    cancel: "Cancel",
    save: "Save",
    // WhatsApp modal
    waiting_scan: "Waiting for device scan...",
    scan_instructions: "Open WhatsApp on your phone, navigate to Settings > Linked Devices, and scan the QR code below.",
    generating_qr: "Generating QR...",
    // Edit store profile modal
    edit_store_profile: "Edit Store Profile",
    tap_logo_upload: "Tap logo to upload image",
    store_name: "Store Name",
    monthly_sales_goal: "Monthly Sales Goal (RM)",
    store_category: "Store Category",
    map_location_coords: "MAP LOCATION COORDINATES",
    latitude: "Latitude",
    longitude: "Longitude",
    validation_error: "Validation Error",
    store_name_required: "Store Name is required.",
    email_required: "Business Email is required.",
    profile_updated: "Store profile updated successfully!",
    update_error: "Update Error",
    failed_update_profile: "Failed to update store profile.",
    // Edit operating hours
    edit_operating_hours: "Edit Operating Hours",
    closed: "Closed",
    hours_updated: "Operating hours updated successfully!",
    save_error: "Save Error",
    failed_save_hours: "Failed to save operating hours.",
    // Days
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    // Security modal
    change_password: "Change Password",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    enter_new_password: "Enter new password",
    enter_confirm_password: "Confirm new password",
    password_mismatch: "New password and confirmation do not match.",
    password_length: "Password must be at least 8 characters long.",
    password_updated: "Password updated successfully!",
    password_update_failed: "Failed to update password.",
    // Categories
    food: "Food & Drink",
    retail: "Retail",
    beauty: "Beauty & Salon",
    health: "Health",
    entertainment: "Entertainment",
    other: "Services / Other"
  },
  ms: {
    merchant_portal: "Portal Peniaga",
    merchant_console: "Konsol Peniaga",
    loyalty_wallet: "Dompet Kesetiaan",
    home: "Utama",
    explore: "Teroka",
    vouchers: "Baucar",
    history: "Sejarah",
    customers: "Pelanggan",
    scan_member: "Imbas Ahli",
    marketing: "Pemasaran",
    quick_actions: "Tindakan Pantas",
    recent_activity: "Aktiviti Terkini",
    active_promotions: "Promosi Aktif",
    welcome_back: "Selamat kembali",
    total_stamps_awarded: "Jumlah Setem Diberikan",
    scan_customer_qr: "Imbas QR Pelanggan",
    this_months_sales: "Jualan Bulan Ini",
    goal: "sasaran",
    to_go: "lagi!",
    recent_stamps_issued: "Setem Diberikan Baru-baru Ini",
    see_all: "Lihat Semua",
    no_recent_activities: "Tiada Aktiviti Baru-baru Ini",
    stamps_issued_desc: "Setem yang diberikan dalam tempoh ini akan dipaparkan di sini.",
    stamps_label: "setem",
    today: "Hari Ini",
    this_week: "Minggu Ini",
    this_month: "Bulan Ini",
    every_visit_rewarded: "Setiap kunjungan, diberi ganjaran.",
    show_my_qr_code: "Tunjukkan Kod QR Saya",
    discover_shops: "Teroka Kedai",
    my_stamp_cards: "Kad Setem Saya",
    add_card: "Tambah Kad",
    no_active_cards: "Tiada Kad Aktif",
    no_active_cards_desc: "Mulakan melawat rakan kongsi peniaga kami untuk mengumpul setem dan memperoleh ganjaran!",
    promo_title: "Hujung Minggu Setem 2x",
    promo_badge: "TERHAD",
    promo_desc: "Lawati mana-mana kedai rakan kongsi RISEV hujung minggu ini dan peroleh setem berganda!",
    explore_now: "Teroka Sekarang",
    profile: "Profil",
    // Customers Screen
    transaction_history: "Sejarah Transaksi",
    total_stamps_distributed: "Jumlah Setem Diberikan",
    from_last_month: "dari bulan lepas",
    points_redeemed: "Ganjaran Ditebus",
    rewards_claimed: "ganjaran ditebus oleh pelanggan",
    active_members: "Ahli Aktif",
    no_active_members: "Tiada ahli aktif",
    search_customer: "Cari Pelanggan...",
    all: "Semua",
    purchase: "Pembelian",
    redemption: "Penebusan",
    adjustment: "Pelarasan",
    date_time: "TARIKH & MASA",
    customer: "PELANGGAN",
    type: "JENIS",
    pending: "Belum Selesai",
    success: "Berjaya",
    no_transactions: "Tiada Transaksi",
    no_transactions_desc: "Tiada transaksi pelanggan yang sepadan dengan penapis anda.",
    customer_details: "Butiran Pelanggan",
    phone: "Telefon",
    joined: "Sertai",
    tier_label: "Tahap",
    stamps_collected: "Setem Dikumpul",
    points_balance: "Baki Mata",
    active_vouchers: "Baucar Aktif",
    export_data: "Eksport Data",
    download_csv: "Muat Turun CSV",
    date_filter: "Penapis Tarikh",
    all_time: "Semua Masa",
    yesterday: "Semalam",
    last_7_days: "7 Hari Lepas",
    last_30_days: "30 Hari Lepas",
    sort_by: "Susun Mengikut",
    newest: "Terbaru Dahulu",
    oldest: "Terlama Dahulu",
    customer_profile: "Profil Pelanggan",
    redemption_details: "Butiran Penebusan",
    reward_item: "Butiran Ganjaran",
    voucher_code: "Kod Baucar",
    redeemed_at: "Ditebus Pada",
    stamp_card_progress: "PROGRES KAD SETEM",
    current_stamps: "Setem Semasa",
    total_completions: "Jumlah Selesai",
    completed: "Selesai",
    no_active_card_desc: "Tiada kad setem aktif dimulakan lagi.",
    rewards_vouchers: "GANJARAN & BAUCAR",
    no_vouchers_desc: "Tiada baucar dikeluarkan untuk pelanggan ini.",
    visit_history: "SEJARAH LAWATAN",
    earned_stamp: "Setem Diperoleh",
    redeemed_reward: "Ganjaran Ditebus",
    no_visits_desc: "Tiada lawatan dicatatkan.",
    filter_by_date: "Tapis Mengikut Tarikh",
    sort_preferences: "Pilihan Susunan",
    sort_by_date: "SUSUN MENGIKUT TARIKH",
    export_data_csv: "Eksport Data ke CSV",
    compiling_csv: "Menyusun fail eksport CSV...",
    customer_database: "Pangkalan Data Pelanggan",
    customer_database_sub: "Termasuk nama, nombor telefon, tahap, dan baki mata.",
    filtered_transactions: "Transaksi Ditapis",
    filtered_transactions_sub: "Mengeksport rekod yang sepadan dengan tetapan penapis semasa sahaja.",
    all_time_transactions: "Transaksi Sepanjang Masa",
    all_time_transactions_sub: "Log sejarah transaksi penuh termasuk jumlah bil subjumlah.",
    // Scan / Manual Input
    scan_qr_code: "Imbas Kod QR",
    manual_input: "Input Manual",
    scan_subtitle: "Jajarkan kod QR pelanggan dalam bingkai pemidang tilik untuk mengkreditkan mata setem secara automatik.",
    manual_stamp_or_voucher: "Setem atau Baucar Manual",
    manual_subtitle: "Masukkan nombor telefon pelanggan untuk mengkreditkan setem, atau masukkan kod baucar (bermula dengan WV- atau RV-) untuk menebus.",
    phone_number_or_voucher: "NOMBOR TELEFON ATAU KOD BAUCAR",
    phone_or_voucher_placeholder: "+60123456789 atau WV-XXXX/RV-XXXX",
    bill_subtotal: "SUBJUMLAH BIL (RM)",
    stamps_to_issue: "BILANGAN SETEM UNTUK DIBERIKAN",
    issue_stamps_btn: "Berikan Mata Setem",
    submitting: "Menghantar...",
    issue_success_title: "Setem Berjaya Diberikan!",
    issue_success_desc: "Berjaya mengkreditkan setem kepada pelanggan.",
    camera_permission_required: "Akses kamera diperlukan untuk mengimbas kod QR.",
    enable_camera: "Aktifkan Kamera",
    redeem_voucher: "Tebus Baucar",
    voucher_redeemed_upper: "BAUCAR DITEBUS!",
    stamps_awarded_upper: "SETEM DIBERIKAN!",
    awarded: "Diberikan",
    bill_amount: "Jumlah Bil",
    current_balance: "Baki Semasa",
    reward: "Ganjaran",
    done: "SELESAI",
    new_customer_profile: "PROFIL PELANGGAN BARU",
    customer_name_optional: "NAMA PELANGGAN (PILIHAN)",
    customer_name_placeholder: "Masukkan nama (cth. Adam)",
    create_issue: "Cipta & Berikan",
    campaign_inactive: "KEMPEN TIDAK AKTIF",
    campaign_inactive_desc: "Tiada program kesetiaan aktif ditemui untuk kedai anda. Sila pergi ke bahagian Pemasaran untuk mencipta kempen dan mengaktifkannya terlebih dahulu.",
    close: "Tutup",
    go_to_marketing: "Pergi ke Pemasaran",
    // Marketing Screen
    promotions: "Promosi",
    broadcast: "Hebahan",
    marketing_campaigns: "Kempen Pemasaran",
    marketing_subtitle: "Tingkatkan jualan kedai dengan pengganda dan promosi mata.",
    new_btn: "+ Baru",
    no_active_promotions: "Tiada promosi aktif lagi",
    no_promotions_desc: "Lancarkan kempen mata berganda atau bonus rata untuk menarik pelanggan ke kedai anda.",
    create_campaign: "Cipta Kempen",
    whatsapp_disconnected: "WhatsApp Terputus",
    whatsapp_disconnected_desc: "Sila pautkan WhatsApp kedai anda di Tetapan Profil untuk menghantar promosi.",
    instant_blast: "Hantar Serta-merta",
    auto_follow_up: "Susulan Automatik",
    compose_broadcast: "Gubal Hebahan Segera",
    compose_subtitle: "Sesuaikan templat promosi atau taip kemas kini tersuai.",
    link_campaign: "PAUTAN KEMPEN (PILIHAN)",
    no_campaign_link: "Tiada Pautan Kempen",
    broadcast_title: "TAJUK HEBAHAN",
    message_body: "KANDUNGAN MESEJ (BERTEMPLAT)",
    send_broadcast: "Hantar Hebahan",
    promotion_type: "JENIS PROMOSI",
    campaign_period: "TEMPOH KEMPEN",
    redemptions: "Penebusan",
    unlimited_placeholder: "Tanpa had jika dibiarkan kosong",
    template_helper_desc: "Gunakan {{name}} untuk nama pelanggan dan {{stamps}} untuk bilangan setem yang dikumpul.",
    send_whatsapp_message: "Hantar Mesej WhatsApp",
    whatsapp_blast_desc: "Menghantar mesej interaksi tinggi selain daripada makluman aplikasi.",
    send_broadcast_btn: "Hantar Hebahan Serta-merta",
    broadcast_history: "SEJARAH HEBAHAN",
    no_broadcasts_sent: "Tiada hebahan dihantar lagi",
    no_broadcasts_desc: "Pautkan WhatsApp anda dan hantar hebahan promosi pertama anda!",
    sent_on: "Dihantar pada",
    recipients: "PENERIMA",
    follow_up: "Susulan",
    follow_up_on: "Susulan pada",
    edit_automation_rule: "Edit Peraturan Susulan Pengekalan",
    automated_winback: "Susulan Automatik Pelanggan Lama",
    automation_desc: "Berikan amaran secara automatik kepada pelanggan selepas mereka tidak aktif untuk beberapa hari yang ditetapkan sejak lawatan/setem terakhir mereka.",
    trigger_delay: "PENCETUS KELEWATAN TIDAK AKTIF",
    days: "Hari",
    custom: "Tersuai",
    custom_days_placeholder: "Masukkan bilangan hari tersuai (cth. 10)",
    rule_name: "NAMA PERATURAN",
    message_title: "TAJUK MESEJ",
    send_via_whatsapp: "Hantar melalui WhatsApp",
    whatsapp_automation_desc: "Menghantar pemberitahuan terus ke WhatsApp pelanggan apabila dicetuskan.",
    update_rule: "Kemas Kini Peraturan",
    activate_rule: "Aktifkan Peraturan Automasi",
    cancel_edit: "Batal Edit",
    active_automation_rules: "PERATURAN AUTOMASI AKTIF",
    no_automation_rules: "Tiada peraturan automasi lagi",
    no_automation_desc: "Takrifkan peraturan pertama anda di atas untuk membuat susulan secara automatik pada pelanggan yang tidak aktif.",
    trigger_label: "Pencetus",
    days_inactive: "Hari Tidak Aktif",
    subject: "Subjek",
    edit: "Edit",
    delete: "Padam",
    launch_campaign: "Lancarkan Kempen",
    campaign_name: "NAMA KEMPEN",
    description: "KETERANGAN",
    point_multiplier: "PENGGANDA MATA",
    flat_points_value: "NILAI MATA RATA",
    bonus_stamps_awarded: "SETEM BONUS DIBERIKAN",
    double_points: "Mata Berganda",
    flat_bonus: "Bonus Rata",
    bonus_stamps: "Setem Bonus",
    start_date: "TARIKH MULA",
    end_date: "TARIKH TAMAT",
    max_redemptions: "PENEBUSAN MAKSIMUM (PILIHAN)",
    launch_promotion_btn: "Lancarkan Promosi",
    store_owner_only: "Pemilik Kedai Sahaja",
    store_owner_only_desc: "Panel konfigurasi ini terhad kepada pemilik kedai peniaga sahaja. Sila hubungi pentadbir anda untuk membuat kemas kini reka bentuk.",
    go_back_home: "Kembali ke Utama",
    // Rewards Screen
    rewards_catalog: "Katalog Ganjaran",
    rewards_desc: "Sediakan dan urus katalog ganjaran untuk penebusan setem",
    create_reward: "Cipta Ganjaran",
    experience: "Pengalaman",
    cash_credit: "Kredit Tunai",
    catalogue_tab: "Katalog",
    card_design_tab: "Reka Bentuk Kad",
    points_tiers_tab: "Mata & Tahap",
    loyalty_settings: "Tetapan Kesetiaan",
    rewards_loyalty_setup: "Butiran Kesetiaan & Ganjaran",
    rewards_loyalty_setup_desc: "Konfigurasikan pengalaman kesetiaan pelanggan, butiran kad visual, peraturan mata, dan katalog ganjaran anda.",
    catalogue_empty: "Katalog Kosong",
    catalogue_empty_desc: "Anda belum menambah sebarang ganjaran untuk ditebus oleh pelanggan anda lagi. Klik butang \"+\" di bahagian atas kanan untuk mencipta ganjaran pertama anda!",
    add_first_reward: "Tambah Ganjaran Pertama",
    enable_loyalty_program: "Aktifkan Program Kesetiaan",
    enable_loyalty_desc: "Aktifkan atau jeda program setem kesetiaan ini untuk kedai anda dengan serta-merta.",
    total_stamps_required: "Jumlah Setem Diperlukan",
    total_stamps_desc: "Tetapan bilangan setem yang diperlukan untuk melengkapkan ganjaran.",
    card_bg_color: "Warna Latar Belakang Kad",
    custom_hex_code: "Kod Hex Tersuai",
    collected_slots_color: "Warna Slot Setem yang Dikumpul",
    select_card_text_color: "Pilih Warna Teks Kad",
    stamp_check_icon: "Ikon Semak Setem",
    stamp_check_desc: "Pilih simbol semak visual yang dipaparkan dalam slot setem yang telah diperoleh.",
    custom_bg_image: "Imej Latar Belakang Tersuai",
    custom_bg_desc: "Muat naik imej jenama landskap tindanan untuk belakang kad anda. Disyorkan: 800x450, maks 2MB.",
    upload_card_image: "Muat Naik Imej Kad",
    card_settings: "Tetapan Kad",
    card_expiration_days: "Tempoh tamat kad (hari)",
    stamp_completion_desc: "Keterangan ganjaran penyiapan setem",
    live_preview_card: "KAD PRATINJAU LANGSUNG",
    loyalty_card_upper: "KAD KESETIAAN",
    card_holder: "PEMEGANG KAD",
    valid: "SAH",
    cvv: "CVV",
    save_card_config: "Simpan Konfigurasi Kad",
    how_points_work: "Bagaimana Pelanggan Anda Memperoleh Mata",
    how_points_work_desc: "Setiap kali pelanggan membayar di kedai anda, mereka memperoleh mata kesetiaan berdasarkan jumlah perbelanjaan mereka.",
    formula_label: "RM 1 dibelanjakan = 1 Mata",
    example_label: "📋 Contoh",
    example_desc: "Pelanggan membayar RM 45.50 untuk pesanan mereka.\nMereka menerima 45 mata ditambah pada kad kesetiaan mereka — secara automatik!",
    points_added_info: "Mata ditambah setiap kali kakitangan anda memasukkan kunjungan pelanggan. Tiada langkah tambahan diperlukan daripada pelanggan.",
    membership_tiers: "Tahap Keahlian Pelanggan",
    membership_tiers_desc: "Pelanggan meningkat tahap berdasarkan jumlah perbelanjaan mereka di kedai anda dalam tempoh 12 bulan yang lalu. Tahap yang lebih tinggi memperoleh lebih banyak mata untuk setiap ringgit — memberi ganjaran kepada pelanggan paling setia anda secara automatik.",
    bronze_desc: "Pelanggan baru · Jumlah perbelanjaan bawah RM 100",
    silver_desc: "Pelanggan biasa · RM 100 – RM 299 dibelanjakan",
    gold_desc: "Pelanggan setia · RM 300 – RM 499 dibelanjakan",
    platinum_desc: "Pelanggan VIP · RM 500+ dibelanjakan",
    points_multiplier_label: "1x Mata",
    points_multiplier_silver: "1.25x Mata",
    points_multiplier_gold: "1.5x Mata",
    points_multiplier_platinum: "2x Mata",
    why_tiers_matter: "Mengapa tahap keahlian penting untuk perniagaan anda",
    why_tiers_matter_desc: "Pelanggan Platinum memperoleh 2x mata untuk setiap ringgit, yang mendorong pembelanja terbaik anda untuk terus kembali. Tahap keahlian dijejak dan dikemas kini secara automatik — anda tidak perlu melakukan apa-apa.",
    add_new_reward: "Tambah Ganjaran Baru",
    edit_reward: "Edit Ganjaran",
    upload_image: "Muat Naik Imej",
    reward_title: "Tajuk Ganjaran",
    points_cost: "Kos Mata",
    stock_availability: "Ketersediaan Stok",
    reward_type: "Jenis Ganjaran",
    description_terms: "Keterangan / Terma",
    describe_terms_placeholder: "Terangkan keterangan ganjaran dan terma penebusan...",
    publish_reward: "Terbitkan Ganjaran",
    publish_reward_desc: "Jadikan ganjaran ini kelihatan kepada pelanggan dengan serta-merta.",
    save_changes: "Simpan Perubahan",
    delete_reward: "Padam Ganjaran",
    delete_reward_confirm: "Adakah anda pasti mahu memadamkan ganjaran ini daripada katalog anda? Tindakan ini tidak boleh diubah.",
    // Staff Screen
    invite_staff: "Jemput Kakitangan",
    manage_staff: "Urus Kakitangan",
    manage_staff_desc: "Berikan kebenaran kepada kakitangan untuk menguruskan kedai anda, memberikan mata setem, dan memproses penebusan ganjaran.",
    add_staff_desc: "Masukkan nombor telefon pelanggan untuk menjemput mereka sebagai kakitangan. Mereka mesti sudah mempunyai akaun dalam Aplikasi Pelanggan.",
    add_btn_label: "Tambah",
    active_staff: "Kakitangan Aktif",
    no_staff: "Tiada Kakitangan Ditambah Lagi",
    no_staff_desc: "Anda kini menguruskan kedai ini bersendirian. Gunakan borang di atas untuk menambah juruwang atau pengurus cawangan anda.",
    remove_staff: "Alih Keluar Kakitangan",
    email: "EMEL",
    role: "PERANAN",
    profile_settings: "Profil & Tetapan",
    profile_subtitle: "Urus profil perniagaan kedai dan pilihan akaun anda.",
    verified_partner: "RAKAN KONGSI DISAHKAN",
    gold_partner: "RAKAN KONGSI EMAS",
    update: "Kemaskini",
    business_email: "EMEL PERNIAGAAN",
    phone_number: "NOMBOR TELEFON",
    address: "ALAMAT",
    personal_account: "Akaun Peribadi?",
    switch_customer_desc: "Tukar kembali ke konsol pelanggan untuk melihat kad kesetiaan dan ganjaran katalog anda.",
    switch_customer_btn: "Tukar ke Mod Pelanggan",
    operating_hours: "Waktu Operasi",
    account_settings: "Tetapan Akaun",
    link_whatsapp: "Pautkan WhatsApp",
    link_whatsapp_desc: "Pautkan akaun WhatsApp kedai",
    whatsapp_connected: "Disambung (Ketik untuk urus)",
    whatsapp_checking: "Menyemak status...",
    manage_rewards: "Urus Ganjaran",
    manage_rewards_desc: "Sediakan dan urus katalog ganjaran",
    notifications: "Pemberitahuan",
    notifications_desc: "Makluman Tolak, E-mel & SMS",
    security: "Keselamatan",
    security_desc: "Tetapan kata laluan",
    language: "Bahasa",
    language_desc: "Bahasa Melayu",
    payment_method: "Kaedah Pembayaran",
    payment_method_desc: "Kredit & Pindahan Bank",
    privacy_policy: "Dasar Privasi",
    privacy_policy_desc: "Terma & Syarat",
    logout: "Log Keluar",
    logout_desc: "Tamatkan sesi aktif",
    logout_confirm_title: "Log Keluar Akaun",
    logout_confirm_desc: "Adakah anda pasti mahu log keluar dari akaun RISEV anda? Anda perlu mengesahkan nombor telefon bimbit anda sekali lagi untuk log masuk semula.",
    cancel: "Batal",
    save: "Simpan",
    // WhatsApp modal
    waiting_scan: "Menunggu imbasan peranti...",
    scan_instructions: "Buka WhatsApp di telefon anda, pergi ke Tetapan > Peranti Pautan, dan imbas kod QR di bawah.",
    generating_qr: "Menjana QR...",
    // Edit store profile modal
    edit_store_profile: "Edit Profil Kedai",
    tap_logo_upload: "Ketik logo untuk memuat naik imej",
    store_name: "Nama Kedai",
    monthly_sales_goal: "Sasaran Jualan Bulanan (RM)",
    store_category: "Kategori Kedai",
    map_location_coords: "KOORDINAT LOKASI PETA",
    latitude: "Latitud",
    longitude: "Longitud",
    validation_error: "Ralat Pengesahan",
    store_name_required: "Nama kedai diperlukan.",
    email_required: "E-mel perniagaan diperlukan.",
    profile_updated: "Profil kedai berjaya dikemas kini!",
    update_error: "Ralat Kemas Kini",
    failed_update_profile: "Gagal mengemas kini profil kedai.",
    // Edit operating hours
    edit_operating_hours: "Edit Waktu Operasi",
    closed: "Tutup",
    hours_updated: "Waktu operasi berjaya dikemas kini!",
    save_error: "Ralat Menyimpan",
    failed_save_hours: "Gagal menyimpan waktu operasi.",
    // Days
    monday: "Isnin",
    tuesday: "Selasa",
    wednesday: "Rabu",
    thursday: "Khamis",
    friday: "Jumaat",
    saturday: "Sabtu",
    sunday: "Ahad",
    // Security modal
    change_password: "Tukar Kata Laluan",
    new_password: "Kata Laluan Baru",
    confirm_password: "Sahkan Kata Laluan Baru",
    enter_new_password: "Masukkan kata laluan baru",
    enter_confirm_password: "Sahkan kata laluan baru",
    password_mismatch: "Kata laluan baru dan pengesahan tidak sepadan.",
    password_length: "Kata laluan mestilah sekurang-kurangnya 8 aksara.",
    password_updated: "Kata laluan berjaya dikemas kini!",
    password_update_failed: "Gagal mengemas kini kata laluan.",
    // Categories
    food: "Makanan & Minuman",
    retail: "Runcit",
    beauty: "Kecantikan & Salon",
    health: "Kesihatan",
    entertainment: "Hiburan",
    other: "Perkhidmatan / Lain-lain"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocaleState] = useState<Locale>('en');

  useEffect(() => {
    const loadLocale = async () => {
      const stored = await storage.getItem('risev_locale');
      if (stored === 'en' || stored === 'ms') {
        setLocaleState(stored);
      }
    };
    loadLocale();
  }, []);

  const setLocale = async (newLocale: Locale) => {
    setLocaleState(newLocale);
    await storage.setItem('risev_locale', newLocale);
  };

  const t = (key: string): string => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
