// lib/push-notifications.ts
// Client-side helper for PWA Web Push notifications registration and subscription

import { pb } from './pocketbase';
import { Platform } from 'react-native';

export type PushPermissionStatus = 'granted' | 'denied' | 'default' | 'unsupported';

/**
 * Checks if the current browser/device environment supports Web Push.
 */
export function isPushSupported(): boolean {
  if (Platform.OS !== 'web' || typeof window === 'undefined') {
    return false;
  }
  return 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window;
}

/**
 * Returns the current notification permission status.
 */
export function getPushPermissionStatus(): PushPermissionStatus {
  if (!isPushSupported()) return 'unsupported';
  return Notification.permission as PushPermissionStatus;
}

/**
 * Converts a base64-encoded VAPID public key into a Uint8Array required by pushManager.subscribe.
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Registers the root service worker if not already registered.
 */
export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!isPushSupported()) return null;
  try {
    const registration = await navigator.serviceWorker.register('/sw.js', { scope: '/' });
    await navigator.serviceWorker.ready;
    return registration;
  } catch (err) {
    console.warn('[PUSH CLIENT] Service Worker registration failed:', err);
    return null;
  }
}

/**
 * Requests permission and subscribes the user's browser/PWA to Web Push notifications.
 */
export async function subscribeToPushNotifications(options?: {
  merchantId?: string;
  branchId?: string;
}): Promise<{ success: boolean; message?: string }> {
  if (!isPushSupported()) {
    return { success: false, message: 'Web Push is not supported on this browser or platform.' };
  }

  try {
    // 1. Request Browser Notification Permission
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return { success: false, message: 'Permission not granted by user.' };
    }

    // 2. Ensure Service Worker is active
    const registration = await registerServiceWorker();
    if (!registration) {
      return { success: false, message: 'Failed to initialize Service Worker.' };
    }

    // 3. Fetch VAPID Public Key from PocketBase
    const keyRes = await pb.send('/api/risev/push/vapid-key', { method: 'GET' });
    const publicKey = keyRes?.publicKey;

    if (!publicKey) {
      return { success: false, message: 'Failed to obtain VAPID public key.' };
    }

    const applicationServerKey = urlBase64ToUint8Array(publicKey);

    // 4. Subscribe via Browser PushManager
    let subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: applicationServerKey as any,
      });
    }

    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      return { success: false, message: 'Invalid subscription generated by browser.' };
    }

    // 5. Detect device description
    const userAgent = navigator.userAgent;
    let deviceName = 'Browser';
    if (/android/i.test(userAgent)) deviceName = 'Android Device';
    else if (/iphone|ipad|ipod/i.test(userAgent)) deviceName = 'iOS Device';
    else if (/mac/i.test(userAgent)) deviceName = 'Mac Desktop';
    else if (/win/i.test(userAgent)) deviceName = 'Windows Desktop';

    // 6. Save subscription to PocketBase
    await pb.send('/api/risev/push/subscribe', {
      method: 'POST',
      body: {
        endpoint: subJson.endpoint,
        keys: {
          p256dh: subJson.keys.p256dh,
          auth: subJson.keys.auth,
        },
        device: deviceName,
        merchant_id: options?.merchantId,
        branch_id: options?.branchId,
      },
    });

    console.log('[PUSH CLIENT] Successfully subscribed to Web Push notifications!');
    return { success: true, message: 'Notifications enabled successfully.' };
  } catch (err: any) {
    console.error('[PUSH CLIENT SUBSCRIBE ERROR]', err);
    return { success: false, message: err?.message || 'Failed to enable notifications.' };
  }
}

/**
 * Unsubscribes the current device.
 */
export async function unsubscribeFromPushNotifications(): Promise<boolean> {
  if (!isPushSupported()) return false;

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();
    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();
      try {
        await pb.send('/api/risev/push/unsubscribe', {
          method: 'POST',
          body: { endpoint },
        });
      } catch (e) {}
    }
    return true;
  } catch (err) {
    console.error('[PUSH CLIENT UNSUBSCRIBE ERROR]', err);
    return false;
  }
}

/**
 * Sends a test push notification to the logged-in merchant.
 */
export async function sendTestPushNotification(): Promise<boolean> {
  try {
    const res = await pb.send('/api/risev/push/test', { method: 'POST' });
    return !!res?.success;
  } catch (err) {
    console.error('[PUSH CLIENT TEST ERROR]', err);
    return false;
  }
}
